Feat/tag
Tracktor/treege pull request #17
Opened 2023-10-06 08:51 UTC by badreleglil

2023-10-09 08:19 UTC, MickaelAustoni requested changes

2023-10-09 08:19 UTC, MickaelAustoni commented on package.json
> +  "version": "0.12",
`0.12.0` pour respecter la convention de versionning

2023-10-09 08:19 UTC, MickaelAustoni commented on CHANGELOG.md
> +- **[feat]** : Can add a tag per node
```suggestion
- **[feat]** :  Add possibility to add a tag to each tree node
```

2023-10-09 08:19 UTC, MickaelAustoni commented on src/utils/tree/getNodeTags/getNodeTags.ts
> +      nodeTags.add(node?.attributes?.tag);
Ici tu peux supprimer l'optional chaining et faire directement :

```suggestion
      nodeTags.add(node.attributes.tag);
```
car tu test déjà si il y un tag `if (node?.attributes?.tag) {`

2023-10-09 08:19 UTC, MickaelAustoni commented on src/utils/tree/getNodeTags/getNodeTags.ts
> +    if (node.children && node.children.length > 0) {
Plus simple :

```suggestion
if (node?.children?.length) {
```

2023-10-09 08:19 UTC, MickaelAustoni commented on src/utils/tree/getNodeTags/getNodeTags.ts
> +  return Array.from(nodeTags);
```suggestion
  return [...nodeTags];
```

2023-10-09 08:19 UTC, MickaelAustoni commented on src/utils/tree/getNodeTags/getNodeTags.ts
> + * Get node names from tree
```suggestion
 * Get node tags from tree
```

PS: Toutes les opti proposé pour ce fichier peuvent d'ailleurs être effectué sur `getNodeNames()`

2023-10-09 08:19 UTC, MickaelAustoni commented on src/features/Treege/components/FieldCreatableSelect/FieldSelectCreatable.tsx
> +import { Autocomplete, createFilterOptions, TextField } from "@tracktor/design-system";
J'ai juste un petit soucis avec le nom de ce composant `FieldSelectCreatable`. `FieldSelectAutocomplete` ?

2023-10-09 13:06 UTC, badreleglil commented on src/features/Treege/components/FieldCreatableSelect/FieldSelectCreatable.tsx
> +import { Autocomplete, createFilterOptions, TextField } from "@tracktor/design-system";
Il est aussi `creatable` d'ou l’interêt de le mettre dans le nom,  `FieldSelectAutocompleteCreatable`?

2023-10-10 08:29 UTC, MickaelAustoni approved these changes

2023-10-10 08:29 UTC, merged