feat(dateRange): add date range type into treege
Tracktor/treege pull request #20
Opened 2024-01-22 16:40 UTC by graffkevin

2024-01-22 17:00 UTC, MickaelAustoni requested changes

2024-01-22 17:00 UTC, MickaelAustoni commented on src/constants/fields.ts
> +    type: "dateRangePicker",
Ici je mettrais `dateRange` cr dernière c'est pas forcément un picker

2024-01-23 13:58 UTC, graffkevin commented on src/constants/fields.ts
> +    type: "dateRangePicker",
changement fait !

2024-01-23 14:02 UTC, MickaelAustoni approved these changes

2024-01-23 14:02 UTC, merged