feat(autocomplete): add path to values for autocompletion API
Tracktor/treege pull request #21
Opened 2024-02-06 13:51 UTC by graffkevin

2024-02-06 15:49 UTC, MickaelAustoni requested changes

2024-02-06 15:49 UTC, MickaelAustoni commented on src/features/Treege/components/Forms/FormTreeCardMutation/FormTreeCardMutation.tsx
> +            <Stack spacing={3} sx={{ p: 1 }} direction={{ sm: "row", xs: "column" }} alignItems="center">
```suggestion
            <Stack spacing={1} sx={{ pb: 1 }} direction={{ sm: "row", xs: "column" }} alignItems="center">
```

2024-02-06 15:49 UTC, MickaelAustoni commented on src/features/Treege/components/Forms/FormTreeCardMutation/FormTreeCardMutation.tsx
> +            <Stack spacing={3} sx={{ p: 1 }} direction={{ sm: "row", xs: "column" }} alignItems="center">
```suggestion
            <Stack spacing={1} direction={{ sm: "row", xs: "column" }} alignItems="center">
```

2024-02-06 15:49 UTC, MickaelAustoni commented on src/features/Treege/components/Forms/FormTreeCardMutation/FormTreeCardMutation.tsx
Et ligne 207 supprimer le `paddingY` :

<Stack spacing={1} direction={{ sm: "row", xs: "column" }}>

2024-02-06 15:49 UTC, MickaelAustoni commented on src/features/Treege/components/Forms/FormTreeCardMutation/useFormTreeCardMutation.ts
> +        dataPath: {
J'ai juste un petit doute sur le dataPath non ? On peu trouver mieux ?  `pathKey` ?

2024-02-06 21:11 UTC, graffkevin commented on src/features/Treege/components/Forms/FormTreeCardMutation/FormTreeCardMutation.tsx
> +            <Stack spacing={3} sx={{ p: 1 }} direction={{ sm: "row", xs: "column" }} alignItems="center">
c'est reglé :)

2024-02-06 21:11 UTC, graffkevin commented on src/features/Treege/components/Forms/FormTreeCardMutation/FormTreeCardMutation.tsx
> +            <Stack spacing={3} sx={{ p: 1 }} direction={{ sm: "row", xs: "column" }} alignItems="center">
corrigé

2024-02-06 21:12 UTC, graffkevin commented on src/features/Treege/components/Forms/FormTreeCardMutation/useFormTreeCardMutation.ts
> +        dataPath: {
en effet plus parlant 👍

2024-02-06 21:12 UTC, graffkevin commented on src/features/Treege/components/Forms/FormTreeCardMutation/FormTreeCardMutation.tsx
ca marche

2024-02-06 21:13 UTC, graffkevin commented
@MickaelAustoni (et @badreleglil ) attention j'ai ajouté un nouveau système d'intégration de params complémentaire dans le dernier commit

2024-02-06 21:14 UTC, graffkevin commented
ca permet d'avoir la forme suivante:
```JSON
{
  "attributes": {
    "depth": 0,
    "label": "1",
    "type": "autocomplete",
    "route": {
      "params": [
        {
          "id": "0",
          "key": "a",
          "value": "b"
        },
        {
          "id": "1",
          "key": "c",
          "value": "d"
        }
      ],
      "pathKey": {
        "image": "",
        "label": "",
        "object": "",
        "value": ""
      },
      "searchKey": "q",
      "url": "http://localhost:5174/"
    },
    "isLeaf": true,
    "isRoot": true
  },
  "children": [],
  "name": "1"
}
```

2024-02-06 21:15 UTC, graffkevin commented
c'est à dire des params de la forme {id, key, value}[]

2024-02-06 21:16 UTC, graffkevin commented
<img width="557" alt="Capture d’écran 2024-02-06 à 22 15 59" src="https://github.com/Tracktor/treege/assets/51543682/1220e03c-a7fa-4f70-893e-e05f9627f36f">

2024-02-06 21:45 UTC, MickaelAustoni requested changes
Très très nice comme feature @graffkevin je kiffffff 💪🔥🔥🔥

J'aurais juste deux petit retour après avoir testé : 

- Ça serait bien de pouvoir supprimer un extra param (comme pour les options d'un select par exemple) car sinon tu es obligé de supprimer ton `treeNode` et si il à beaucoup d'enfant tu perd tout 😅 
- Ça serait d'avoir les params et/ou pathKey uniquement si il y à de la data dans l'object. Ex: avec un champs ApiAutocomplete sans pathKey et params :
![Capture d’écran 2024-02-06 à 22 41 37](https://github.com/Tracktor/treege/assets/108873902/563cad3b-0ad3-47b5-9a74-157ddd6c6919)

2024-02-07 13:59 UTC, graffkevin commented
j'ai ajouté la fonctionnalité :) c'etait pas simple surtout le fait de pouvoir rendre l'ajout/suppresion de key dynamique mais mainteannt ca fonctionne

2024-02-07 14:08 UTC, graffkevin commented
j'ai tout mis a jour (j'ai vu après que tu l'avais fais aussi) je te laisse test et voir si faut changer des trucs

2024-02-07 14:14 UTC, MickaelAustoni requested changes

2024-02-07 14:14 UTC, MickaelAustoni commented on src/features/Treege/components/Forms/FormTreeCardMutation/FormTreeCardMutation.tsx
> +  const { object: routeObject, label: routeLabel, value: routeValue, image: routeImage } = pathKey || {};
Il y a une erreur quand tu commence à saisir un champ de `pathKey` car tu passe d'un champs `uncontrolled` à `controlled`. Pour éviter ce genre d'erreur il faut initialiser la valeur de ta state car si value est `undefined` ton champ est considérer comme `uncontrolled`.

![Capture d’écran 2024-02-07 à 15 08 57](https://github.com/Tracktor/treege/assets/108873902/920f56dd-a1be-45f4-8c28-903ff0e7678f)


Pour le fix (met toi à jour avant sur ta branch car j'ai merge master dessus et ajouter la new version) : 

```suggestion
  const { object: routeObject = "", label: routeLabel = "", value: routeValue = "", image: routeImage = "" } = pathKey || {};
```

2024-02-07 14:34 UTC, graffkevin commented on src/features/Treege/components/Forms/FormTreeCardMutation/FormTreeCardMutation.tsx
> +  const { object: routeObject, label: routeLabel, value: routeValue, image: routeImage } = pathKey || {};
j'ai fais la modif !

2024-02-07 14:35 UTC, MickaelAustoni approved these changes

2024-02-07 14:35 UTC, merged