Tree field type
Tracktor/treege pull request #5
Opened 2022-10-07 13:56 UTC by badreleglil

2022-10-10 09:48 UTC, MickaelAustoni requested changes
Avant tout, "really good job" frero vraiment 💪

 1. Dans `utils/tree` faire un index avec l'export de toute les fonctions
 2. Faire un dossier `test` pour y mettre les mocks + test

2022-10-10 09:48 UTC, MickaelAustoni commented on src/constants/forbiddenCharacters.ts
> +const forbiddenCharacters = [":", "$"];
Cette constante est utilisé null part.

2022-10-10 09:48 UTC, MickaelAustoni commented on src/utils/tree/getNodeNames/getNodeNames.ts
> +    // const hasTree = key === "attributes" && "tree" in value;
Commentaire à supprimer

2022-10-10 09:48 UTC, MickaelAustoni commented on src/features/DecisionTreeGenerator/reducer/treeReducer.ts
>  const treeReducer = (state: any, action: any) => {
ici tu peu mettre "tree" à la place de state avec un type `TreeNode` (a faire sur toute les actions du reducer)

2022-10-11 07:47 UTC, MickaelAustoni requested changes

2022-10-11 07:47 UTC, MickaelAustoni commented on src/utils/tree/getNodeNames/getNodeNames.ts
> -    // const hasTree = key === "attributes" && "tree" in value;
Supprimer le commentaire

2022-10-11 07:47 UTC, MickaelAustoni commented on src/utils/tree/index.ts
> +import appendChild from "./appendChild/appendChild";
Harmoniser les noms des fonctions

2022-10-11 08:56 UTC, MickaelAustoni requested changes

2022-10-11 08:56 UTC, MickaelAustoni commented on src/utils/tree/index.ts
> +export { getTree, updatedNode, appendNode, removeNode };
Et pourquoi pas getNode ?

ou alors

export { getTreeNode, updatedTreeNode, appendTreeNode, removeTreeNode };

?

2022-10-11 09:06 UTC, badreleglil commented on src/utils/tree/index.ts
> +export { getTree, updatedNode, appendNode, removeNode };
Je me disais qu'un Node fait forcement partie d'un Tree donc je trouvais ca un peu redondant

2022-10-12 08:21 UTC, MickaelAustoni approved these changes

2022-10-12 08:21 UTC, merged